Another changes on main page
Neology92/wielopokoleniowi-website pull request #5
Opened 2021-02-20 15:39 UTC by jvneck

2021-02-20 15:48 UTC, jvneck commented
Próbując dodawać kursywę w treści coś się popsuło. Nie chciała się dać zamknąć przez </i> więc zamykałem ją <i/>, może w tym jest problem. Poza tym są tu 4 inne zmiany, które wcześniej nie miały problemów, ale nie wiem jak zrobić tylko część brancha

2021-02-23 20:06 UTC, Neology92 requested changes

2021-02-23 20:06 UTC, Neology92 commented on src/layouts/mainPageSections/welcomeSection.js
> +        dobrym miejscu. <i>Wielopokoleniowi<i/>to blog sukcesji, mądrym budowaniu
Tagi zamyka się w drugą stronę
```suggestion
        dobrym miejscu. <i>Wielopokoleniowi</i>to blog sukcesji, mądrym budowaniu

```

2021-02-23 20:08 UTC, Neology92 commented
Zaciągnąłeś wcześniejsze zmiany przed otworzeniem tego brancha? Jeśli nie, to zaciągnij sobie mastera 
```
git checkout master
git pull origin master
```
Po czym zmerguj go do aktualnego brancha
```
git checkout this-branch
git merge master
```

I wypchnij tutaj.

2023-05-09 20:51 UTC, closed without merging